language: cpp
compiler:
 - gcc
git:
 submodules: false

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - boost-latest
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - libboost1.55-all-dev
#      env:
#         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

#before_install:
# - eval "${MATRIX_EVAL}"
# - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
# - sudo apt-get update -qq
#install:
# # g++4.8.1
# - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
# - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi
os:
 - linux
script:
    cd src && make cpu

